// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "chat-box.h"

ChatBoxUI::ChatBoxUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 300, "Chat with name");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Output* o = new Fl_Output(0, 0, 385, 260);
      o->color((Fl_Color)46);
      o->labeltype(FL_NO_LABEL);
      o->align(Fl_Align(133));
    } // Fl_Output* o
    { Fl_Input* o = new Fl_Input(0, 270, 330, 30, "input:");
      o->labeltype(FL_NO_LABEL);
    } // Fl_Input* o
    { Fl_Return_Button* o = new Fl_Return_Button(330, 270, 70, 30, "Send");
      o->color((Fl_Color)230);
    } // Fl_Return_Button* o
    { Fl_Scrollbar* o = new Fl_Scrollbar(385, 0, 15, 260);
      o->labeltype(FL_NO_LABEL);
    } // Fl_Scrollbar* o
    o->end();
  } // Fl_Double_Window* o
}
