// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "new_chat.h"

NewChat::NewChat() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 200, "New Chat");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Input* o = new Fl_Input(20, 32, 225, 22, "Address/Alias");
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Input* o
    { Fl_Value_Input* o = new Fl_Value_Input(20, 82, 80, 22, "Request Amount (TGC)");
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Input* o
    { new Fl_Button(325, 170, 64, 20, "Send");
    } // Fl_Button* o
    { new Fl_Button(255, 170, 64, 20, "Cancel");
    } // Fl_Button* o
    { Fl_Input* o = new Fl_Input(20, 132, 225, 22, "First Message");
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Input* o
    o->end();
  } // Fl_Double_Window* o
}
