// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef new_alias_h
#define new_alias_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Text_Display.H>

class NewAlias {
public:
  NewAlias();
};
#endif
