// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef new_chat_h
#define new_chat_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>

class NewChat {
public:
  NewChat();
};
#endif
