// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef settings_h
#define settings_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Input.H>

class Settings {
public:
  Settings();
};
#endif
