// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "settings.h"

Settings::Settings() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 150, "Settings");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { new Fl_Button(325, 120, 64, 20, "Save");
    } // Fl_Button* o
    { Fl_Value_Input* o = new Fl_Value_Input(20, 32, 80, 22, "Chain Request Amount (TGC)");
      o->maximum(1e+08);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Input* o
    { Fl_Value_Input* o = new Fl_Value_Input(20, 81, 80, 22, "Exclusivity");
      o->minimum(-1);
      o->maximum(1e+11);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Input* o
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
}
